parser: babel-eslint
extends: airbnb

env:
  browser: true
  es6: true

rules:
  import/prefer-default-export: 0
  no-unused-expressions: 0
  indent: [2, 2]
  import/no-extraneous-dependencies: 0
  no-empty: 0
  no-else-return: ["error", { allowElseIf: true }]
  no-param-reassign: 0
  react/jsx-filename-extension: 0

settings:
  import/resolver:
    webpack:
      config: "webpack.config.js"
