version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: onsite/components-react
    container_name: onsite-components-react
    ports:
      - 9001:9001
    volumes:
      - .:/usr/src/app
    command: yarn storybook
